# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "nvme" "mpt3sas" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#	fileSystems."/store" = {
#  	device = "UUID=464bb7e4-c23e-4611-a864-941a07bf6a46";
#    fsType = "bcachefs";
#	};
  #fileSystems."/store" = 
  #  {
	#		 device = "/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N0MAR4RJ:/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N0M3REZC:/dev/disk/by-id/ata-WDCWD30EFRX-68EUZN0_WD-WCC4N6FT8CJC:/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N4PP8377:/dev/disk/by-id/ata-CT1000P3SSD8_2307E6ABF4BC:/dev/disk/by-id/ata-ST4000VN008-2DR166_ZGY6VHBS:/dev/disk/by-id/ata-ST4000VN008-2DR166_ZM40Z1YD:/dev/disk/by-id/ata-ST4000VN008-2DR166_ZM40ZH68 /store"
  #    fsType = "bcachefs";
	#		options = [ "nofail" ];
  #  };

  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/b63e8238-c734-4fec-8177-ef4620562217";
  #    fsType = "btrfs";
  #    options = [ "compress=zstd" "subvol=root" ];
  #  };

  #fileSystems."/home" =
  #  { device = "/dev/disk/by-uuid/b63e8238-c734-4fec-8177-ef4620562217";
  #    fsType = "btrfs";
  #    options = [ "compress=zstd" "subvol=home" ];
  #  };

  #fileSystems."/nix" =
  #  { device = "/dev/disk/by-uuid/b63e8238-c734-4fec-8177-ef4620562217";
  #    fsType = "btrfs";
  #    options = [ "compress=zstd" "noatime" "subvol=nix" ];
  #  };

  #fileSystems."/var" =
  #  { device = "/dev/disk/by-uuid/b63e8238-c734-4fec-8177-ef4620562217";
  #    fsType = "btrfs";
  #    options = [ "compress=zstd" "subvol=var" ];
  #  };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/58D1-CCCD";
  #    fsType = "vfat";
  #  };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
