# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "lscr.io/linuxserver/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/store/downloads/complete:/downloads:rw"
      "/store/downloads/incomplete:/incomplete-downloads:rw"
      "/store/service-data/sabnzbd/config:/config:rw"
    ];
    ports = [
      "8083:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sabnzbd"
      "--network=sabznbd_default"
    ];
  };
  systemd.services."podman-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sabznbd_default.service"
    ];
    requires = [
      "podman-network-sabznbd_default.service"
    ];
    partOf = [
      "podman-compose-sabznbd-root.target"
    ];
    wantedBy = [
      "podman-compose-sabznbd-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-sabznbd_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f sabznbd_default";
    };
    script = ''
      podman network inspect sabznbd_default || podman network create sabznbd_default
    '';
    partOf = [ "podman-compose-sabznbd-root.target" ];
    wantedBy = [ "podman-compose-sabznbd-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sabznbd-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
