keys:
  - &users:
    - &derek age1z5spvnd65hudndxv3j784vrxgzsgnxhwjxc20f4kkk6a4ag05qlsm5pwlj
  - &hosts:
    - &luxuria age1thxt9typy9r6sqmqk94ttnec43hqmg8j7j87qv84ved6nlq28esqhjpt0m
    - &gula age19e0kzr3dy4vdt0a5c5ngd28zkatnqc45sghnpecw0zzcrgsltpyq30cdpm
    - &superbia age10cggct4jrne2ursqgzqpsz8mzzfypk5vpza3sddkuqu8ktr0xcwqzhp9xg
    - &anywhere age1qpc3yk2g08xjj84802uk3mu67nhpm0txenqa4ynnueekhznq09ts6pklnf
    - &clusteragent1 age1qpc3yk2g08xjj84802uk3mu67nhpm0txenqa4ynnueekhznq09ts6pklnf
creation_rules:
 - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
   key_groups:
      - age:
          - *derek
          - *luxuria
          - *gula
          - *superbia
 - path_regex: anywhere\.(yaml|json|env|ini)$
   key_groups:
      - age:
          - *anywhere
          - *gula
          - *superbia
          - *luxuria
          - *derek
 - path_regex: k3s\.(yaml|json|env|ini)$
   key_groups:
      - age:
          - *gula
          - *superbia
          - *derek
          - *clusteragent1
